"""initial schema

Revision ID: 9a6037a68657
Revises: 
Create Date: 2026-09-17 17:45:15.711919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6037a68657'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_name', sa.String(length=32), nullable=False),
    sa.Column('mac_type', sa.String(length=8), nullable=False),
    sa.Column('ip_addr', sa.String(length=45), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_mac_name'), 'machines', ['mac_name'], unique=True)
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('shift_day', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_code'), 'operators', ['code'], unique=True)
    op.create_table('report_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_prefs_key'), 'report_prefs', ['key'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('shift_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('shift_mode', sa.Integer(), nullable=False),
    sa.Column('simple', sa.Text(), nullable=True),
    sa.Column('day_start_time', sa.String(length=8), nullable=False),
    sa.Column('schedule_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('beam_type', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_styles_name'), 'styles', ['name'], unique=True)
    op.create_table('agg_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.String(length=32), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('style', sa.String(length=64), nullable=True),
    sa.Column('beam', sa.String(length=32), nullable=True),
    sa.Column('ubeam', sa.String(length=32), nullable=True),
    sa.Column('seisan_1', sa.Float(), nullable=True),
    sa.Column('seisan_2', sa.Float(), nullable=True),
    sa.Column('seisan_3', sa.Float(), nullable=True),
    sa.Column('off_prod_1', sa.Float(), nullable=True),
    sa.Column('off_prod_2', sa.Float(), nullable=True),
    sa.Column('off_prod_3', sa.Float(), nullable=True),
    sa.Column('run_tm', sa.Float(), nullable=True),
    sa.Column('stop_ttm', sa.Float(), nullable=True),
    sa.Column('effic', sa.Float(), nullable=True),
    sa.Column('stop_ct', sa.JSON(), nullable=True),
    sa.Column('stop_tm', sa.JSON(), nullable=True),
    sa.Column('wf1_ct', sa.JSON(), nullable=True),
    sa.Column('wf1_tm', sa.JSON(), nullable=True),
    sa.Column('wf2_ct', sa.JSON(), nullable=True),
    sa.Column('wf2_tm', sa.JSON(), nullable=True),
    sa.Column('lh_ct', sa.JSON(), nullable=True),
    sa.Column('lh_tm', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agg_shift_machine_id'), 'agg_shift', ['machine_id'], unique=False)
    op.create_index(op.f('ix_agg_shift_operator_id'), 'agg_shift', ['operator_id'], unique=False)
    op.create_index(op.f('ix_agg_shift_shift_id'), 'agg_shift', ['shift_id'], unique=False)
    op.create_table('daily_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('seisan', sa.JSON(), nullable=True),
    sa.Column('run_tm', sa.Integer(), nullable=True),
    sa.Column('stop_ttm', sa.Integer(), nullable=True),
    sa.Column('s_ct', sa.JSON(), nullable=True),
    sa.Column('s_tm', sa.JSON(), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_raw_day'), 'daily_raw', ['day'], unique=False)
    op.create_index(op.f('ix_daily_raw_machine_id'), 'daily_raw', ['machine_id'], unique=False)
    op.create_table('machine_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.String(length=32), nullable=True),
    sa.Column('get_time', sa.DateTime(), nullable=True),
    sa.Column('sys_time', sa.DateTime(), nullable=True),
    sa.Column('rtc_time', sa.DateTime(), nullable=True),
    sa.Column('style', sa.String(length=64), nullable=True),
    sa.Column('beam', sa.String(length=32), nullable=True),
    sa.Column('ubeam', sa.String(length=32), nullable=True),
    sa.Column('s_beam', sa.String(length=32), nullable=True),
    sa.Column('r_beam', sa.String(length=32), nullable=True),
    sa.Column('cloth_len', sa.String(length=32), nullable=True),
    sa.Column('cut_len', sa.String(length=32), nullable=True),
    sa.Column('doff_fcst', sa.Integer(), nullable=True),
    sa.Column('wout_fcst', sa.Integer(), nullable=True),
    sa.Column('uwout_fcst', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_snapshots_machine_id'), 'machine_snapshots', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_snapshots_shift_id'), 'machine_snapshots', ['shift_id'], unique=False)
    op.create_table('stop_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.String(length=32), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('stop_time', sa.Integer(), nullable=False),
    sa.Column('run_time', sa.Integer(), nullable=False),
    sa.Column('raw_code', sa.String(length=16), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('stop_start', sa.DateTime(), nullable=True),
    sa.Column('stop_end', sa.DateTime(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_events_day'), 'stop_events', ['day'], unique=False)
    op.create_index(op.f('ix_stop_events_machine_id'), 'stop_events', ['machine_id'], unique=False)
    op.create_index(op.f('ix_stop_events_shift_id'), 'stop_events', ['shift_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stop_events_shift_id'), table_name='stop_events')
    op.drop_index(op.f('ix_stop_events_machine_id'), table_name='stop_events')
    op.drop_index(op.f('ix_stop_events_day'), table_name='stop_events')
    op.drop_table('stop_events')
    op.drop_index(op.f('ix_machine_snapshots_shift_id'), table_name='machine_snapshots')
    op.drop_index(op.f('ix_machine_snapshots_machine_id'), table_name='machine_snapshots')
    op.drop_table('machine_snapshots')
    op.drop_index(op.f('ix_daily_raw_machine_id'), table_name='daily_raw')
    op.drop_index(op.f('ix_daily_raw_day'), table_name='daily_raw')
    op.drop_table('daily_raw')
    op.drop_index(op.f('ix_agg_shift_shift_id'), table_name='agg_shift')
    op.drop_index(op.f('ix_agg_shift_operator_id'), table_name='agg_shift')
    op.drop_index(op.f('ix_agg_shift_machine_id'), table_name='agg_shift')
    op.drop_table('agg_shift')
    op.drop_index(op.f('ix_styles_name'), table_name='styles')
    op.drop_table('styles')
    op.drop_table('shift_schedules')
    op.drop_table('settings')
    op.drop_index(op.f('ix_report_prefs_key'), table_name='report_prefs')
    op.drop_table('report_prefs')
    op.drop_index(op.f('ix_operators_code'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_machines_mac_name'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
